print("Hello, World!")
print("My favourite colour is purple.")
name = input('Whats your name? ')
print(f'Greetings {name} ')
age = input('How old are you? ')
print(f'{name} your are very old since you are {age}')